#!/usr/bin/env python3
"""Generate Codex plugin metadata from the Claude Code marketplace catalog."""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import os
import re
import sys
import tempfile
from collections.abc import Callable, Iterable, Iterator
from contextlib import contextmanager, suppress
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any, TypedDict

import portalocker
import yaml
from yaml.resolver import BaseResolver

SEMVER_PATTERN = re.compile(
    r"^(0|[1-9]\d*)\."
    r"(0|[1-9]\d*)\."
    r"(0|[1-9]\d*)"
    r"(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?"
    r"(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$"
)
SKILL_NAME_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
GITHUB_REPOSITORY_PATTERN = re.compile(
    r"^[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?/[A-Za-z0-9_.-]+$"
)
GENERATOR_PATH = "scripts/generate_codex_marketplace.py"
GENERATED_MARKER = f"Generated by {GENERATOR_PATH}; do not edit."
AGENT_TEAM_ROUTER_THRESHOLD = 4
# Agent Skills caps descriptions at 1024 characters; Claude commands, agents and
# marketplace entries do not.
SKILL_DESCRIPTION_LIMIT = 1024
CLAUDE_MARKETPLACE = Path(".claude-plugin/marketplace.json")
CODEX_MARKETPLACE = Path(".agents/plugins/marketplace.json")
OWNERSHIP_INDEX = Path(".agents/plugins/generated-files.json")
SOURCE_OVERRIDES = Path(".agents/plugins/source-overrides.json")
LOCK_FILE = Path(".agents/plugins/.generation.lock")
OWNERSHIP_VERSION = 1
DEFAULT_MARKETPLACE_NAME = "powerful-plugins"
DEFAULT_AUTHOR_URL = "https://github.com/StackOneHQ"
DEFAULT_REPOSITORY_URL = "https://github.com/StackOneHQ/powerful-plugins"

_DISPLAY_WORDS = {
    "ai": "AI",
    "api": "API",
    "aws": "AWS",
    "cc": "CC",
    "cdk": "CDK",
    "cli": "CLI",
    "csv": "CSV",
    "github": "GitHub",
    "gitlab": "GitLab",
    "html": "HTML",
    "json": "JSON",
    "mcp": "MCP",
    "md": "Markdown",
    "mysql": "MySQL",
    "oauth": "OAuth",
    "oauth2": "OAuth 2",
    "openai": "OpenAI",
    "pdf": "PDF",
    "postgresql": "PostgreSQL",
    "pr": "PR",
    "qa": "QA",
    "sdk": "SDK",
    "seo": "SEO",
    "sql": "SQL",
    "sso": "SSO",
    "to": "to",
    "ui": "UI",
    "url": "URL",
    "ux": "UX",
}


class GenerationError(ValueError):
    """Raised when source marketplace metadata cannot be converted safely."""


class _UniqueKeyLoader(yaml.SafeLoader):
    """Safe YAML loader that rejects ambiguous duplicate mapping keys."""


def _construct_unique_mapping(
    loader: _UniqueKeyLoader, node: yaml.MappingNode, deep: bool = False
) -> dict[Any, Any]:
    loader.flatten_mapping(node)
    mapping: dict[Any, Any] = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=deep)
        if key in mapping:
            raise yaml.constructor.ConstructorError(
                "while constructing a mapping",
                node.start_mark,
                f"found duplicate key {key!r}",
                key_node.start_mark,
            )
        mapping[key] = loader.construct_object(value_node, deep=deep)
    return mapping


_UniqueKeyLoader.add_constructor(
    BaseResolver.DEFAULT_MAPPING_TAG, _construct_unique_mapping
)


@dataclass(frozen=True)
class GeneratedSkill:
    """Codex skill files rendered from one Claude command or agent."""

    name: str
    source: Path
    skill_md: str
    openai_yaml: str


@dataclass(frozen=True)
class ExternalSource:
    """A Claude external plugin source, pinned to one upstream commit."""

    repo: str
    path: str | None
    sha: str


_EXTERNAL_SOURCE_KEYS = {
    "github": {"source", "repo", "sha"},
    "git-subdir": {"source", "url", "path", "sha"},
}


def parse_external_source(source: dict[str, object]) -> ExternalSource:
    """Validate a pinned ``github`` or ``git-subdir`` source; return its repository, path and commit."""
    kind = source.get("source")
    if not isinstance(kind, str) or kind not in _EXTERNAL_SOURCE_KEYS:
        raise GenerationError(
            f"unsupported external source: {kind!r}; use github or git-subdir"
        )
    if kind == "github" and "path" in source:
        raise GenerationError(
            "a github source cannot select a subdirectory: Claude Code ignores its path "
            "and installs the whole repository; use git-subdir with url, path and sha"
        )
    if "ref" in source:
        raise GenerationError(
            "external sources pin a commit with sha, not ref; a ref is a branch or tag "
            "and can move"
        )
    allowed = _EXTERNAL_SOURCE_KEYS[kind]
    missing = sorted(allowed - set(source))
    unknown = sorted(set(source) - allowed)
    if missing or unknown:
        raise GenerationError(
            f"{kind} source must contain exactly {', '.join(sorted(allowed))} "
            f"(missing: {missing}, unexpected: {unknown})"
        )

    repo = source["repo" if kind == "github" else "url"]
    if not isinstance(repo, str) or not GITHUB_REPOSITORY_PATTERN.fullmatch(repo):
        raise GenerationError("external GitHub source must name an owner/repository")
    owner, repository = repo.split("/", 1)
    if (
        owner.endswith("-")
        or repository in {".", ".."}
        or repository.startswith(".")
        or repository.endswith((".", "-", ".git"))
    ):
        raise GenerationError("external GitHub source must include a safe owner/repository")

    sha = source["sha"]
    if not isinstance(sha, str) or not re.fullmatch(r"[0-9a-f]{40}", sha):
        raise GenerationError(
            "external source sha must be a full 40-character lowercase commit SHA"
        )

    path = source.get("path")
    if path is None:
        return ExternalSource(repo, None, sha)
    if (
        not isinstance(path, str)
        or not path
        or path != path.strip()
        or path.startswith(("/", "./"))
        or path.endswith("/")
        or "//" in path
    ):
        raise GenerationError("external source path must be a non-empty relative path")
    if "\\" in path:
        raise GenerationError("external source path must use POSIX separators")
    if ".." in PurePosixPath(path).parts:
        raise GenerationError("external source path must stay inside the repository")
    return ExternalSource(repo, path, sha)


def convert_source(source: dict[str, object]) -> dict[str, object]:
    """Convert a pinned Claude external source into the Codex source for the same commit."""
    parsed = parse_external_source(source)
    converted: dict[str, object] = {
        "source": "url" if parsed.path is None else "git-subdir",
        "url": f"https://github.com/{parsed.repo}.git",
    }
    if parsed.path is not None:
        converted["path"] = f"./{parsed.path}"
    converted["ref"] = parsed.sha
    return converted


def normalize_category(value: str) -> str:
    """Convert marketplace category slugs into human-facing labels."""
    if not isinstance(value, str) or not value.strip():
        raise GenerationError("plugin category must be a non-empty string")
    return " ".join(part.capitalize() for part in re.split(r"[-_\s]+", value.strip()))


def resolve_local_source(root: Path, source: str) -> Path:
    """Resolve a ./-prefixed marketplace source without permitting traversal."""
    if not isinstance(source, str) or not source.startswith("./"):
        raise GenerationError("local plugin source must start with './'")

    resolved_root = root.resolve()
    candidate = (resolved_root / source[2:]).resolve()
    if not candidate.is_relative_to(resolved_root):
        raise GenerationError(f"local plugin source is outside the repository: {source}")
    return candidate


def _display_name(name: str) -> str:
    return " ".join(_DISPLAY_WORDS.get(part, part.capitalize()) for part in name.split("-"))


def _short_description(description: str, limit: int = 120) -> str:
    compact = " ".join(description.split())
    if len(compact) <= limit:
        return compact
    candidate = compact[: limit - 1].rstrip()
    if not compact[limit - 1].isspace() and " " in candidate:
        candidate = candidate.rsplit(" ", 1)[0].rstrip()
    return candidate + "…"


def _ui_short_description(description: str) -> str:
    compact = _short_description(description, 64)
    if len(compact) < 25:
        compact = f"{compact} agent workflow".lstrip()
    if len(compact) < 25:
        compact = f"Run this agent workflow ({compact})"
    return compact


def _sentence_description(description: str) -> str:
    compact = " ".join(description.split())
    if compact.endswith((".", "!", "?", ":", ";")):
        return compact
    return f"{compact}."


def _frontmatter_block(text: str, source: Path) -> tuple[list[str], str]:
    """Return the frontmatter lines, line endings kept, and the Markdown body after them."""
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].rstrip("\r\n") != "---":
        raise GenerationError(f"{source}: missing YAML frontmatter")
    for closing, line in enumerate(lines[1:], start=1):
        if line.rstrip("\r\n") == "---":
            return lines[1:closing], "".join(lines[closing + 1 :]).lstrip("\r\n")
    raise GenerationError(f"{source}: unterminated YAML frontmatter")


def _parse_frontmatter_yaml(
    yaml_text: str, source: Path, loader_class: type[yaml.SafeLoader]
) -> dict[str, Any]:
    loader = loader_class(yaml_text)
    try:
        parsed = loader.get_single_data()
    except yaml.YAMLError as error:
        raise GenerationError(f"{source}: invalid YAML frontmatter: {error}") from error
    finally:
        loader.dispose()  # type: ignore[no-untyped-call]  # PyYAML stubs omit this method's types.
    if parsed is None:
        return {}
    if isinstance(parsed, dict) and all(isinstance(key, str) for key in parsed):
        return parsed
    raise GenerationError(f"{source}: YAML frontmatter must be an object")


def split_frontmatter(
    text: str, source: Path, *, reject_duplicate_keys: bool = True
) -> tuple[dict[str, Any], str]:
    """Parse YAML frontmatter without changing the Markdown body."""
    frontmatter, body = _frontmatter_block(text, source)
    loader_class = _UniqueKeyLoader if reject_duplicate_keys else yaml.SafeLoader
    return _parse_frontmatter_yaml("".join(frontmatter), source, loader_class), body


def _parse_plain_frontmatter(lines: list[str]) -> dict[str, Any] | None:
    """Read ``key: value`` lines and block scalars one at a time; None if a value has a YAML tag."""
    metadata: dict[str, Any] = {}
    index = 0
    while index < len(lines):
        line = lines[index]
        index += 1
        if not line or line[0].isspace() or line.startswith("#") or ":" not in line:
            continue
        key, raw_value = (part.strip() for part in line.split(":", 1))
        if not key:
            continue
        if raw_value in {"|", "|-", "|+", ">", ">-", ">+"}:
            block: list[str] = []
            while index < len(lines) and (not lines[index] or lines[index][0].isspace()):
                block.append(lines[index])
                index += 1
            indentation = min(
                (len(item) - len(item.lstrip()) for item in block if item.strip()),
                default=0,
            )
            if raw_value.startswith(">"):
                metadata[key] = " ".join(item.strip() for item in block if item.strip())
            else:
                metadata[key] = (
                    "\n".join(item[indentation:] for item in block).rstrip("\n") + "\n"
                )
            continue
        if raw_value.startswith("!"):
            return None
        if ": " in raw_value and not raw_value.startswith(("'", '"')):
            metadata[key] = raw_value
            continue
        try:
            metadata[key] = yaml.safe_load(raw_value)
        except yaml.YAMLError:
            metadata[key] = raw_value
    return metadata


def split_claude_frontmatter(text: str, source: Path) -> tuple[dict[str, Any], str]:
    """Parse Claude metadata, including legacy plain scalars that are not strict YAML."""
    frontmatter, body = _frontmatter_block(text, source)
    try:
        return _parse_frontmatter_yaml("".join(frontmatter), source, yaml.SafeLoader), body
    except GenerationError:
        metadata = _parse_plain_frontmatter([line.rstrip("\r\n") for line in frontmatter])
        if not metadata:
            raise
        return metadata, body


def _required_string(metadata: dict[str, Any], key: str, source: Path) -> str:
    value = metadata.get(key)
    if not isinstance(value, str) or not value.strip():
        raise GenerationError(f"{source}: missing or invalid {key}")
    return value.strip()


def _optional_string(metadata: dict[str, Any], key: str, source: Path) -> str | None:
    if metadata.get(key) is None:
        return None
    return _required_string(metadata, key, source)


def _validate_skill_name(name: str, source: Path) -> None:
    if len(name) > 64 or not SKILL_NAME_PATTERN.fullmatch(name):
        raise GenerationError(f"{source}: invalid generated skill name {name!r}")


def _normalize_skill_name(value: str, source: Path) -> str:
    normalized = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    _validate_skill_name(normalized, source)
    return normalized


def _is_semver(value: str) -> bool:
    """Validate SemVer 2.0.0, including numeric prerelease leading-zero rules."""
    if SEMVER_PATTERN.fullmatch(value) is None:
        return False
    prerelease = value.split("+", 1)[0].partition("-")[2]
    return not any(
        identifier.isdigit() and len(identifier) > 1 and identifier.startswith("0")
        for identifier in prerelease.split(".")
    )


def _disables_model_invocation(metadata: dict[str, Any]) -> bool:
    disabled = metadata.get("disable-model-invocation")
    return disabled is True or disabled == "true"


def _agent_identity(metadata: dict[str, Any], source: Path) -> tuple[str, str]:
    name = metadata.get("name", source.stem)
    if not isinstance(name, str) or not name.strip():
        raise GenerationError(f"{source}: invalid agent name")
    description = metadata.get("description")
    if isinstance(description, str) and description.strip():
        return name, description.strip()
    return name, f"{_display_name(name)} specialist workflow."


def render_openai_yaml(name: str, description: str, *, implicit: bool) -> str:
    """Render deterministic Codex UI and invocation metadata for a skill."""
    return (
        f"# {GENERATED_MARKER}\n"
        "interface:\n"
        f"  display_name: {json.dumps(_display_name(name), ensure_ascii=False)}\n"
        f"  short_description: {json.dumps(_ui_short_description(description), ensure_ascii=False)}\n"
        f"  default_prompt: {json.dumps(f'Use ${name} to run this workflow.', ensure_ascii=False)}\n"
        "policy:\n"
        f"  allow_implicit_invocation: {'true' if implicit else 'false'}\n"
    )


def _render_adapter(
    *,
    name: str,
    description: str,
    source: Path,
    body: str,
    argument_hint: str | None = None,
    implicit: bool = False,
) -> GeneratedSkill:
    _validate_skill_name(name, source)
    description = _short_description(description, SKILL_DESCRIPTION_LIMIT)
    title = f"# {_display_name(name)}"
    sections = [
        "---",
        f"name: {name}",
        f"description: {json.dumps(description, ensure_ascii=False)}",
        "---",
        "",
        f"<!-- {GENERATED_MARKER} Source: {source.as_posix()} -->",
        "",
        title,
        "",
    ]
    if argument_hint:
        sections.extend((f"Arguments: `{argument_hint}`", ""))
    body_lines = [line.rstrip() for line in body.splitlines()]
    if body_lines and body_lines[0].strip() == title:
        body_lines.pop(0)
        while body_lines and not body_lines[0]:
            body_lines.pop(0)
    sections.append("\n".join(body_lines))
    return GeneratedSkill(
        name=name,
        source=source,
        skill_md="\n".join(sections).rstrip() + "\n",
        openai_yaml=render_openai_yaml(name, description, implicit=implicit),
    )


def _translate_cc_print_body(body: str, source: Path) -> str:
    """Keep Claude's command unchanged while pointing its Codex adapter at Codex data."""
    if "~/.claude/projects/" not in body or "/scripts/export-conversation.js" not in body:
        return body
    claude_session_lookup = (
        "1. **Find the conversation file**. This session's transcript is named after its id:\n"
        "   ```bash\n"
        "   ls ~/.claude/projects/*/\"${CLAUDE_SESSION_ID}\".jsonl 2>/dev/null | head -1\n"
        "   ```\n"
        "   If that finds nothing, fall back to the newest transcript for this folder. Claude Code names the\n"
        "   folder after the working directory with every character other than a letter or digit turned into `-`:\n"
        "   ```bash\n"
        "   ls -t ~/.claude/projects/\"$(pwd | sed 's/[^A-Za-z0-9]/-/g')\"/*.jsonl 2>/dev/null | head -1\n"
        "   ```"
    )
    codex_session_lookup = (
        "1. **Find the Codex conversation file** (the newest session started in this folder):\n"
        "   ```bash\n"
        "   python3 - <<'PY'\n"
        "   import json, os, pathlib\n"
        "   sessions = pathlib.Path(os.environ.get(\"CODEX_HOME\") or pathlib.Path.home() / \".codex\") / \"sessions\"\n"
        "   here = {os.getcwd(), os.environ.get(\"PWD\")}\n"
        "   for path in sorted(sessions.rglob(\"rollout-*.jsonl\"), key=lambda p: p.stat().st_mtime, reverse=True):\n"
        "       try:\n"
        "           with path.open() as rollout:\n"
        "               meta = json.loads(rollout.readline() or \"{}\")\n"
        "       except (OSError, ValueError):\n"
        "           continue  # a rollout still being written, or unreadable\n"
        "       if meta.get(\"payload\", {}).get(\"cwd\") in here:\n"
        "           print(path)\n"
        "           break\n"
        "   PY\n"
        "   ```\n"
        "   If several sessions ran in this folder at once, confirm with the user which one to export."
    )
    claude_script_lookup = (
        "3. **Find the export script**:\n"
        "   ```bash\n"
        "   printf '%s\\n' \"${CLAUDE_PLUGIN_ROOT}/scripts/export-conversation.js\"\n"
        "   ```"
    )
    codex_script_lookup = (
        "3. **Find the export script**:\n"
        "   ```bash\n"
        "   printf '%s\\n' \"${PLUGIN_ROOT}/scripts/export-conversation.js\"\n"
        "   ```"
    )
    if claude_session_lookup not in body or claude_script_lookup not in body:
        raise GenerationError(f"{source}: unrecognized Claude conversation export command")
    body = body.replace(claude_session_lookup, codex_session_lookup)
    body = body.replace(claude_script_lookup, codex_script_lookup)
    return body.replace("`/cc-print:print", "`$cc-print:codex-print")


_FENCE_PATTERN = re.compile(r"^ {0,3}(`{3,}|~{3,})")
_INLINE_CODE_PATTERN = re.compile(r"(`+)(?:(?!\1).)+?\1")
# `$@` or a positional `$N` that is not part of a larger number such as `$5.00` or `$50`.
_ARGUMENT_PLACEHOLDER_PATTERN = re.compile(r"\$@|\$(\d)(?![\d.,]?\d)")


def _translate_argument_placeholders(text: str) -> str:
    return _ARGUMENT_PLACEHOLDER_PATTERN.sub(
        lambda match: "the invocation input"
        if match.group(0) == "$@"
        else f"invocation argument {match.group(1)}",
        text,
    )


def _replace_outside_code(text: str, replace: Callable[[str], str]) -> str:
    """Apply ``replace`` to prose only, leaving fenced blocks and inline code untouched,
    because shell snippets use ``$1`` and ``$@`` for their own positional parameters."""
    output: list[str] = []
    fence: str | None = None
    for line in text.splitlines(keepends=True):
        match = _FENCE_PATTERN.match(line)
        if fence is not None:
            output.append(line)
            closing = line.strip()
            if match and closing == closing[0] * len(closing) and closing.startswith(fence):
                fence = None
            continue
        if match:
            fence = match.group(1)
            output.append(line)
            continue
        position = 0
        pieces: list[str] = []
        for code in _INLINE_CODE_PATTERN.finditer(line):
            pieces.append(replace(line[position : code.start()]))
            pieces.append(code.group(0))
            position = code.end()
        pieces.append(replace(line[position:]))
        output.append("".join(pieces))
    return "".join(output)


_CLAUDE_VARIABLES = (
    ("${CLAUDE_PLUGIN_ROOT:-${PLUGIN_ROOT:-}}", "${PLUGIN_ROOT}"),
    ("${CLAUDE_PLUGIN_ROOT}", "${PLUGIN_ROOT}"),
    ("$CLAUDE_PLUGIN_ROOT", "${PLUGIN_ROOT}"),
    ("$ARGUMENTS", "the invocation input"),
)
_CLAUDE_TOOL_NAMES = (
    ("AskUserQuestion", "ask the user directly"),
    ("Task tool", "delegation capability"),
    ("`/agents`", "the bundled specialist workflows"),
    ("/agents command", "specialist-workflow picker"),
)


def _translate_claude_body(body: str, source: Path) -> str:
    """Translate common Claude-only placeholders into portable skill language."""
    translated = _translate_cc_print_body(body, source)
    for claude_text, portable_text in _CLAUDE_VARIABLES:
        translated = translated.replace(claude_text, portable_text)
    translated = _replace_outside_code(translated, _translate_argument_placeholders)
    for claude_text, portable_text in _CLAUDE_TOOL_NAMES:
        translated = translated.replace(claude_text, portable_text)
    if "${PLUGIN_ROOT}" in translated:
        translated = (
            "Before running shell snippets, resolve `PLUGIN_ROOT` to the nearest "
            "ancestor containing `.codex-plugin/plugin.json`, and export it.\n\n"
            + translated
        )
    return translated


def render_command_adapter(source: Path, text: str) -> GeneratedSkill:
    """Convert one Claude command file into an explicit Codex skill."""
    metadata, body = split_claude_frontmatter(text, source)
    description = _required_string(metadata, "description", source)
    return _render_adapter(
        name=_normalize_skill_name(f"codex-{source.stem}", source),
        description=description,
        source=source,
        body=_translate_claude_body(body, source),
        argument_hint=_optional_string(metadata, "argument-hint", source),
    )


def render_agent_adapter(source: Path, text: str) -> GeneratedSkill:
    """Convert one Claude specialist agent prompt into an explicit Codex skill."""
    metadata, body = split_claude_frontmatter(text, source)
    agent_name, description = _agent_identity(metadata, source)
    constraint_note = (
        "Codex compatibility: the source agent's model and tool allowlist metadata cannot be "
        "enforced by a skill. Use only the least-privileged capabilities needed for this task, "
        "and preserve the source workflow's intent.\n\n"
    )
    return _render_adapter(
        name=_normalize_skill_name(f"agent-{agent_name}", source),
        description=f"Specialist workflow: {description}",
        source=source,
        body=constraint_note + _translate_claude_body(body, source),
    )


def _render_specialist_router(plugin_dir: Path, agent_files: list[Path]) -> GeneratedSkill:
    routes: list[str] = []
    for agent_file in agent_files:
        metadata, _ = split_claude_frontmatter(_read_text(agent_file), agent_file)
        agent_name, description = _agent_identity(metadata, agent_file)
        routes.append(
            f"- `{agent_name}` — {_sentence_description(description)} Read "
            f"`../../../{agent_file.relative_to(plugin_dir).as_posix()}` "
            "before delegating."
        )
    return _render_adapter(
        name=_normalize_skill_name(f"{plugin_dir.name}-specialists", plugin_dir / "agents"),
        description=(
            f"Route {_display_name(plugin_dir.name)} workflows to the bundled "
            "specialist agent prompts."
        ),
        source=Path("agents"),
        body=(
            "When another workflow delegates to a named specialist, select the "
            "matching prompt below, read it completely, and use it as the "
            "instructions for that delegated task. Source model and tool allowlists "
            "are advisory because Codex skills cannot enforce them; use least privilege.\n\n"
            + "\n".join(routes)
        ),
        implicit=True,
    )


def render_existing_skill_metadata(source: Path, text: str) -> str | None:
    """Map Claude's model-invocation opt-out to Codex policy metadata."""
    metadata, _ = split_claude_frontmatter(text, source)
    if not _disables_model_invocation(metadata):
        return None
    name = _required_string(metadata, "name", source)
    description = _required_string(metadata, "description", source)
    _validate_skill_name(name, source)
    return render_openai_yaml(name, description, implicit=False)


def _text_has_generated_marker(text: str) -> bool:
    return GENERATED_MARKER in "\n".join(text.splitlines()[:8])


def _authored_frontmatter(paths: Iterable[Path]) -> Iterator[tuple[Path, dict[str, Any]]]:
    """Yield each hand-written file with its frontmatter, skipping files this generator wrote."""
    for path in paths:
        contents = _read_text(path)
        if not _text_has_generated_marker(contents):
            yield path, split_claude_frontmatter(contents, path)[0]


def _has_generated_marker(path: Path) -> bool:
    try:
        return _text_has_generated_marker(_read_text(path))
    except (FileNotFoundError, GenerationError):
        return False


def _component_path(plugin_dir: Path, value: str, component: str) -> Path:
    """Return the plugin path a manifest names, refusing symlinks and paths that leave the plugin."""
    if not value or value.startswith("/") or "\\" in value or value != value.strip():
        raise GenerationError(f"{plugin_dir}: invalid {component} component path")
    relative = PurePosixPath(value.removeprefix("./"))
    if not relative.parts or ".." in relative.parts:
        raise GenerationError(f"{plugin_dir}: invalid {component} component path")
    path = plugin_dir
    for part in relative.parts:
        path /= part
        if path.is_symlink():
            raise GenerationError(f"{plugin_dir}: symlinked {component} component path")
    if not path.resolve().is_relative_to(plugin_dir.resolve()):
        raise GenerationError(f"{plugin_dir}: {component} component path escapes plugin")
    return path


def _component_file_reference(plugin_dir: Path, value: str, component: str) -> str:
    path = _component_path(plugin_dir, value, component)
    if not path.is_file():
        raise GenerationError(f"{plugin_dir}: missing {component} component path {value}")
    return f"./{path.relative_to(plugin_dir).as_posix()}"


def _component_files(
    plugin_dir: Path, manifest: dict[str, Any], key: str, filename_pattern: str
) -> list[Path]:
    """Resolve Claude default and custom component paths safely and recursively."""
    default = plugin_dir / key
    if default.is_symlink():
        raise GenerationError(f"{plugin_dir}: symlinked default {key} component path")
    candidates = [default] if default.is_dir() else []
    root_skill = plugin_dir / "SKILL.md"
    if key == "skills" and root_skill.is_file() and not root_skill.is_symlink():
        candidates.append(root_skill)

    configured = manifest.get(key)
    if configured is None:
        configured_paths: list[str] = []
    elif isinstance(configured, str):
        configured_paths = [configured]
    elif isinstance(configured, list) and all(isinstance(item, str) for item in configured):
        configured_paths = configured
    else:
        raise GenerationError(f"{plugin_dir}: {key} component path must be a string or array")
    for configured_path in configured_paths:
        path = _component_path(plugin_dir, configured_path, key).resolve()
        if not path.exists():
            raise GenerationError(f"{plugin_dir}: missing {key} component path {configured_path}")
        candidates.append(path)

    files: set[Path] = set()
    for candidate in candidates:
        if candidate.is_file():
            if candidate.match(filename_pattern):
                files.add(candidate)
        elif candidate.is_dir():
            files.update(
                path
                for path in candidate.rglob(filename_pattern)
                if path.is_file() and not path.is_symlink()
            )
        else:
            raise GenerationError(f"{plugin_dir}: component is not a regular file or directory")
    return sorted(files)


def _add_unique_adapter(
    adapters: dict[str, GeneratedSkill], adapter: GeneratedSkill, plugin_dir: Path
) -> None:
    if adapter.name in adapters:
        raise GenerationError(f"{plugin_dir}: adapter name collision for {adapter.name!r}")
    adapters[adapter.name] = adapter


def collect_adapter_skills(
    plugin_dir: Path, claude_manifest: dict[str, Any] | None = None
) -> dict[str, GeneratedSkill]:
    """Collect collision-free Codex adapters for one local plugin."""
    plugin_dir = plugin_dir.resolve()
    manifest = claude_manifest or {}
    adapters: dict[str, GeneratedSkill] = {}
    native_skills = _component_files(plugin_dir, manifest, "skills", "SKILL.md")
    for skill_file, metadata in _authored_frontmatter(native_skills):
        name = _required_string(metadata, "name", skill_file)
        description = _required_string(metadata, "description", skill_file)
        _validate_skill_name(name, skill_file)
        if name in adapters:
            raise GenerationError(f"{plugin_dir}: duplicate native skill name {name!r}")
        relative = skill_file.relative_to(plugin_dir)
        adapters[name] = _render_adapter(
            name=name,
            description=description,
            source=relative,
            body=(
                f"Read `../../../{relative.as_posix()}` completely, then follow it as "
                "the authoritative workflow. Resolve any relative paths from that source file. "
                "In Codex, treat `CLAUDE_PLUGIN_ROOT` and `PLUGIN_ROOT` as the nearest ancestor "
                "containing `.codex-plugin/plugin.json`."
            ),
            implicit=not _disables_model_invocation(metadata),
        )
    native_names = set(adapters)

    for command_file in _component_files(plugin_dir, manifest, "commands", "*.md"):
        command_source = command_file.relative_to(plugin_dir)
        if _normalize_skill_name(command_file.stem, command_source) in native_names:
            continue
        _add_unique_adapter(
            adapters,
            render_command_adapter(command_source, _read_text(command_file)),
            plugin_dir,
        )

    agent_files = _component_files(plugin_dir, manifest, "agents", "*.md")
    if len(agent_files) >= AGENT_TEAM_ROUTER_THRESHOLD:
        _add_unique_adapter(
            adapters, _render_specialist_router(plugin_dir, agent_files), plugin_dir
        )
    else:
        for agent_file in agent_files:
            _add_unique_adapter(
                adapters,
                render_agent_adapter(agent_file.relative_to(plugin_dir), _read_text(agent_file)),
                plugin_dir,
            )

    skills_root = plugin_dir / "skills"
    if not skills_root.is_dir():
        return adapters
    for group_dir in sorted(path for path in skills_root.iterdir() if path.is_dir()):
        root_skill = group_dir / "SKILL.md"
        if root_skill.is_file() and not _has_generated_marker(root_skill):
            continue
        nested_files = (path for path in sorted(group_dir.rglob("SKILL.md")) if path != root_skill)
        nested_skills = [
            (_required_string(metadata, "name", skill_file), skill_file.relative_to(group_dir))
            for skill_file, metadata in _authored_frontmatter(nested_files)
        ]
        if not nested_skills:
            continue

        group = group_dir.relative_to(plugin_dir)
        router_name = _normalize_skill_name(group_dir.name, group)
        if len(nested_skills) == 1 and nested_skills[0][0] == router_name:
            continue
        if router_name in native_names:
            router_name = _normalize_skill_name(f"{group_dir.name}-router", group)
        if router_name in adapters:
            continue
        nested_routes = "\n".join(
            f"- `{nested_name}`: read `../../../{group.as_posix()}/{relative.as_posix()}`"
            for nested_name, relative in nested_skills
        )
        adapters[router_name] = _render_adapter(
            name=router_name,
            description=(
                f"Route {_display_name(router_name)} requests to the bundled "
                "specialist workflows."
            ),
            source=group,
            body=(
                "Select the workflow that matches the request, read its `SKILL.md` "
                "completely, and follow it.\n\n"
                f"{nested_routes}"
            ),
        )
    return adapters


def build_plugin_manifest(
    plugin_dir: Path,
    entry: dict[str, Any],
    claude_manifest: dict[str, Any],
    *,
    has_adapters: bool = False,
) -> dict[str, Any]:
    """Build one Codex plugin manifest from Claude metadata and local files."""
    name = claude_manifest.get("name")
    if not isinstance(name, str) or not name:
        raise GenerationError(f"{plugin_dir}: Claude manifest is missing name")
    if entry.get("name") != name:
        raise GenerationError(
            f"{plugin_dir}: marketplace name {entry.get('name')!r} does not match {name!r}"
        )

    version = claude_manifest.get("version")
    if not isinstance(version, str) or not _is_semver(version):
        raise GenerationError(f"{plugin_dir}: version must be a semantic version")

    description = claude_manifest.get("description")
    if not isinstance(description, str) or not description.strip():
        raise GenerationError(f"{plugin_dir}: Claude manifest is missing description")

    category = normalize_category(entry.get("category", "Productivity"))
    author = claude_manifest.get("author", entry.get("author"))
    if not isinstance(author, dict) or not author.get("name"):
        raise GenerationError(f"{plugin_dir}: Claude manifest is missing author.name")
    codex_author = copy.deepcopy(author)
    codex_author.setdefault("url", DEFAULT_AUTHOR_URL)
    homepage = claude_manifest.get("homepage", DEFAULT_REPOSITORY_URL)

    manifest: dict[str, Any] = {
        "name": name,
        "version": version,
        "description": description,
        "author": codex_author,
        "homepage": homepage,
        "repository": claude_manifest.get("repository", DEFAULT_REPOSITORY_URL),
        "interface": {
            "displayName": _display_name(name),
            "shortDescription": _short_description(description),
            "longDescription": description,
            "developerName": str(codex_author["name"]),
            "category": category,
            "capabilities": ["Interactive"],
            "websiteURL": homepage,
            "defaultPrompt": [f"Use {_display_name(name)} to run this workflow."],
        },
    }

    license_value = claude_manifest.get("license", entry.get("license"))
    if license_value is not None:
        manifest["license"] = copy.deepcopy(license_value)
    keywords = claude_manifest.get("keywords", entry.get("tags"))
    if keywords is not None:
        manifest["keywords"] = copy.deepcopy(keywords)

    if has_adapters:
        manifest["skills"] = "./.codex/skills/"
    elif any(
        not _text_has_generated_marker(_read_text(skill_file))
        for skill_file in _component_files(plugin_dir, claude_manifest, "skills", "SKILL.md")
    ):
        manifest["skills"] = "./skills/"
    declared_mcp = claude_manifest.get("mcpServers")
    if (plugin_dir / ".codex-mcp.json").is_file():
        manifest["mcpServers"] = _component_file_reference(
            plugin_dir, "./.codex-mcp.json", "mcpServers"
        )
    elif isinstance(declared_mcp, dict):
        manifest["mcpServers"] = copy.deepcopy(declared_mcp)
    elif isinstance(declared_mcp, str):
        manifest["mcpServers"] = _component_file_reference(
            plugin_dir, declared_mcp, "mcpServers"
        )
    elif declared_mcp is not None:
        raise GenerationError(f"{plugin_dir}: mcpServers must be a path or object")
    elif (plugin_dir / ".mcp.json").is_file():
        manifest["mcpServers"] = "./.mcp.json"
    if (plugin_dir / ".app.json").is_file():
        manifest["apps"] = "./.app.json"

    declared_hooks = claude_manifest.get("hooks")
    if declared_hooks is not None:
        if not isinstance(declared_hooks, str):
            raise GenerationError(f"{plugin_dir}: hooks component path must be a string")
        hook_path = _component_file_reference(plugin_dir, declared_hooks, "hooks")
        if hook_path != "./hooks/hooks.json" and not (
            plugin_dir / "hooks" / "hooks.json"
        ).is_file():
            raise GenerationError(
                f"{plugin_dir}: custom Claude hooks require hooks/hooks.json for Codex"
            )

    return manifest


def _read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        raise
    except (OSError, UnicodeError) as error:
        raise GenerationError(f"unable to read {path}: {error}") from error


def _unique_json_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    value: dict[str, Any] = {}
    for key, item in pairs:
        if key in value:
            raise GenerationError(f"duplicate JSON key {key!r}")
        value[key] = item
    return value


def _load_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(_read_text(path), object_pairs_hook=_unique_json_object)
    except FileNotFoundError as error:
        raise GenerationError(f"missing required JSON file: {path}") from error
    except json.JSONDecodeError as error:
        raise GenerationError(f"invalid JSON in {path}: {error}") from error
    if not isinstance(value, dict):
        raise GenerationError(f"{path}: expected a JSON object")
    return value


def _json_text(value: object) -> str:
    return json.dumps(value, indent=2, ensure_ascii=False) + "\n"


def _marketplace_plugins(catalog: dict[str, Any]) -> list[dict[str, Any]]:
    entries = catalog.get("plugins")
    if not isinstance(entries, list):
        raise GenerationError("Claude marketplace must contain a plugins array")
    if not all(isinstance(entry, dict) for entry in entries):
        raise GenerationError("Claude marketplace plugin entries must be objects")
    return entries


def _marketplace_entries(root: Path) -> list[dict[str, Any]]:
    return _marketplace_plugins(_load_json(root / CLAUDE_MARKETPLACE))


def _codex_catalog_entry(
    name: str, entry: dict[str, Any], source: dict[str, object]
) -> dict[str, Any]:
    return {
        "name": name,
        "source": source,
        "policy": {
            "installation": "AVAILABLE",
            "authentication": "ON_INSTALL",
        },
        "category": normalize_category(entry.get("category", "Productivity")),
    }


class _RuntimeAdapterOverride(TypedDict):
    source: str
    entrypoints: list[str]


def _external_source_overrides(root: Path) -> dict[str, _RuntimeAdapterOverride]:
    path = root / SOURCE_OVERRIDES
    if not path.is_file():
        return {}
    value = _load_json(path)
    if value.get("version") != 2 or not isinstance(value.get("plugins"), dict):
        raise GenerationError(f"{SOURCE_OVERRIDES}: unsupported override schema")
    overrides: dict[str, _RuntimeAdapterOverride] = {}
    for name, source in value["plugins"].items():
        if not isinstance(source, dict):
            raise GenerationError(f"{SOURCE_OVERRIDES}: invalid plugin override")
        if source.get("source") != "runtime-adapter":
            raise GenerationError(f"{SOURCE_OVERRIDES}: unsupported override source")
        if set(source) != {"source", "entrypoints"}:
            raise GenerationError(
                f"{SOURCE_OVERRIDES}: runtime adapters may contain only source and entrypoints"
            )
        entrypoints = source["entrypoints"]
        if (
            not isinstance(entrypoints, list)
            or not entrypoints
            or not all(isinstance(item, str) for item in entrypoints)
        ):
            raise GenerationError(f"{SOURCE_OVERRIDES}: invalid runtime adapter metadata")
        for entrypoint in entrypoints:
            normalized = PurePosixPath(entrypoint)
            if (
                normalized.is_absolute()
                or not normalized.parts
                or ".." in normalized.parts
                or "\\" in entrypoint
            ):
                raise GenerationError(f"{SOURCE_OVERRIDES}: invalid adapter entrypoint")
        overrides[name] = {"source": "runtime-adapter", "entrypoints": entrypoints}
    return overrides


def _render_runtime_adapter_skill(
    name: str,
    description: str,
    repo: str,
    ref: str,
    entrypoints: list[str],
) -> str:
    routes = "\n".join(f"- `{entrypoint}`" for entrypoint in entrypoints)
    return (
        "---\n"
        f"name: {name}\n"
        f"description: {json.dumps(description, ensure_ascii=False)}\n"
        "compatibility: Requires Python 3, Git, and HTTPS access to github.com on first use.\n"
        "---\n\n"
        f"<!-- {GENERATED_MARKER} Runtime upstream adapter. -->\n\n"
        f"# {_display_name(name)}\n\n"
        "This adapter loads an upstream workflow at an immutable Git commit. It never follows the "
        "upstream default branch.\n\n"
        "1. From this skill directory, run the bundled materializer and use the verified checkout "
        "path it prints:\n\n"
        "   ```text\n"
        "   python3 scripts/materialize_pinned_upstream.py "
        f"--name {name} --repo {repo} --ref {ref}\n"
        "   ```\n\n"
        "2. Select the entrypoint that matches the request, read it completely from that checkout, "
        "and follow it. "
        "Resolve every relative path from the pinned checkout. If an entrypoint uses Claude-only "
        "tool names or argument placeholders, interpret them by intent using the equivalent Codex "
        "capability and the user's invocation input.\n\n"
        f"{routes}\n"
    )


def _add_runtime_adapter_files(
    root: Path,
    name: str,
    entry: dict[str, Any],
    upstream: ExternalSource,
    entrypoints: list[str],
    expected: dict[Path, str],
) -> Path:
    description = entry.get("description")
    if not isinstance(description, str) or not description.strip():
        raise GenerationError(f"{name}: runtime adapter requires a description")
    adapter_root = Path("codex-compat") / name
    _validate_relative_path(adapter_root)
    if not (root / adapter_root).resolve().is_relative_to(root):
        raise GenerationError(f"{SOURCE_OVERRIDES}: adapter path escapes repository")
    author = entry.get("author")
    if not isinstance(author, dict) or not isinstance(author.get("name"), str):
        raise GenerationError(f"{name}: runtime adapter requires author.name")
    helper = root / "scripts" / "materialize_pinned_upstream.py"
    if not helper.is_file():
        raise GenerationError(f"missing runtime adapter helper: {helper.relative_to(root)}")
    helper_text = _read_text(helper)
    prefix = PurePosixPath(upstream.path or "")
    skill_md = _render_runtime_adapter_skill(
        name,
        _short_description(description, SKILL_DESCRIPTION_LIMIT),
        upstream.repo,
        upstream.sha,
        [(prefix / entrypoint).as_posix() for entrypoint in entrypoints],
    )
    openai_yaml = render_openai_yaml(name, description, implicit=True)
    manifest = {
        "name": name,
        "version": "",
        "description": description,
        "author": author,
        "repository": f"https://github.com/{upstream.repo}",
        "skills": "./skills/",
        "interface": {
            "displayName": _display_name(name),
            "shortDescription": _short_description(description),
            "longDescription": description,
            "developerName": author["name"],
            "category": normalize_category(entry.get("category", "Productivity")),
            "capabilities": ["Interactive"],
            "websiteURL": f"https://github.com/{upstream.repo}",
            "defaultPrompt": [f"Use {_display_name(name)} for this workflow."],
        },
    }
    # Installs are cached per version, so the version must change whenever any installed
    # file does: the pinned commit, the helper, the instructions, the policy or the manifest.
    bundle = "\0".join((helper_text, skill_md, openai_yaml, _json_text(manifest)))
    bundle_digest = hashlib.sha256(bundle.encode("utf-8")).hexdigest()[:12]
    manifest["version"] = f"0.1.0+{upstream.sha[:12]}.{bundle_digest}"
    expected[adapter_root / ".codex-plugin" / "plugin.json"] = _json_text(manifest)
    skill_root = adapter_root / "skills" / name
    expected[skill_root / "SKILL.md"] = skill_md
    expected[skill_root / "scripts" / helper.name] = helper_text
    expected[skill_root / "agents" / "openai.yaml"] = openai_yaml
    return adapter_root


def _add_local_plugin_files(
    root: Path,
    plugin_dir: Path,
    entry: dict[str, Any],
    expected: dict[Path, str],
) -> None:
    claude_manifest = _load_json(plugin_dir / ".claude-plugin" / "plugin.json")
    adapters = collect_adapter_skills(plugin_dir, claude_manifest)
    codex_manifest = build_plugin_manifest(
        plugin_dir, entry, claude_manifest, has_adapters=bool(adapters)
    )
    plugin_relative = plugin_dir.relative_to(root)
    expected[plugin_relative / ".codex-plugin" / "plugin.json"] = _json_text(codex_manifest)

    for adapter in adapters.values():
        adapter_root = plugin_relative / ".codex" / "skills" / adapter.name
        existing_skill = root / adapter_root / "SKILL.md"
        if existing_skill.exists() and not _has_generated_marker(existing_skill):
            raise GenerationError(
                f"{plugin_dir}: adapter destination is human-authored: {adapter_root}"
            )
        expected[adapter_root / "SKILL.md"] = adapter.skill_md
        expected[adapter_root / "agents" / "openai.yaml"] = adapter.openai_yaml


def build_expected_files(root: Path) -> dict[Path, str]:
    """Build the complete generated repository view without writing it."""
    root = root.resolve()
    source_catalog = _load_json(root / CLAUDE_MARKETPLACE)
    entries = _marketplace_plugins(source_catalog)
    unclaimed_adapters = _external_source_overrides(root)

    expected: dict[Path, str] = {}
    codex_entries: list[dict[str, Any]] = []
    seen_names: set[str] = set()
    for entry in entries:
        name = entry.get("name")
        if not isinstance(name, str) or not name:
            raise GenerationError("marketplace entry is missing a plugin name")
        if name in seen_names:
            raise GenerationError(f"duplicate marketplace plugin name: {name}")
        seen_names.add(name)

        source = entry.get("source")
        codex_source: dict[str, object]
        if isinstance(source, str):
            plugin_dir = resolve_local_source(root, source)
            if not plugin_dir.is_dir():
                raise GenerationError(f"local plugin directory does not exist: {source}")
            plugin_path = f"./{plugin_dir.relative_to(root).as_posix()}"
            codex_source = {"source": "local", "path": plugin_path}
            codex_entries.append(_codex_catalog_entry(name, entry, codex_source))
            _add_local_plugin_files(root, plugin_dir, entry, expected)
            continue
        if not isinstance(source, dict):
            raise GenerationError(f"{name}: source must be a local path or source object")
        try:
            upstream = parse_external_source(source)
        except GenerationError as error:
            raise GenerationError(f"{name}: {error}") from error
        override = unclaimed_adapters.pop(name, None)
        if override is None:
            codex_source = convert_source(source)
        else:
            adapter_root = _add_runtime_adapter_files(
                root, name, entry, upstream, override["entrypoints"], expected
            )
            codex_source = {"source": "local", "path": f"./{adapter_root.as_posix()}"}
        codex_entries.append(_codex_catalog_entry(name, entry, codex_source))

    if unclaimed_adapters:
        raise GenerationError(
            f"{SOURCE_OVERRIDES}: unknown external plugins: {', '.join(sorted(unclaimed_adapters))}"
        )

    catalog_name = source_catalog.get("name", DEFAULT_MARKETPLACE_NAME)
    if not isinstance(catalog_name, str) or not SKILL_NAME_PATTERN.fullmatch(catalog_name):
        raise GenerationError("Claude marketplace name must be a lowercase kebab-case string")
    expected[CODEX_MARKETPLACE] = _json_text(
        {
            "name": catalog_name,
            "interface": {"displayName": _display_name(catalog_name)},
            "plugins": codex_entries,
        }
    )
    expected[OWNERSHIP_INDEX] = _json_text(
        {
            "generatedBy": GENERATOR_PATH,
            "version": OWNERSHIP_VERSION,
            "files": sorted(path.as_posix() for path in [*expected, OWNERSHIP_INDEX]),
        }
    )
    return dict(sorted(expected.items(), key=lambda item: item[0].as_posix()))


def _validate_relative_path(relative: Path) -> None:
    if relative.is_absolute() or not relative.parts or ".." in relative.parts:
        raise GenerationError(f"generated path must stay inside the repository: {relative}")


def _safe_path(root: Path, relative: Path, *, create_parents: bool = False) -> Path:
    """Return a contained path, rejecting every existing symlink component."""
    _validate_relative_path(relative)
    current = root
    for part in relative.parts[:-1]:
        current = current / part
        try:
            current.lstat()
        except FileNotFoundError:
            if not create_parents:
                continue
            with suppress(FileExistsError):
                current.mkdir()
        if current.is_symlink():
            raise GenerationError(f"refusing symlinked generated path: {relative}")
        if not current.is_dir():
            raise GenerationError(f"generated parent is not a directory: {current}")

    destination = root / relative
    if destination.is_symlink():
        raise GenerationError(f"refusing symlinked generated path: {relative}")
    if destination.exists() and not destination.is_file():
        raise GenerationError(f"generated destination is not a file: {relative}")
    return destination


def _load_ownership_index(root: Path) -> set[Path]:
    index_path = root / OWNERSHIP_INDEX
    if not index_path.exists():
        return set()
    value = _load_json(index_path)
    if value.get("generatedBy") != GENERATOR_PATH:
        raise GenerationError(f"{OWNERSHIP_INDEX}: invalid ownership index")
    files = value.get("files")
    if not isinstance(files, list) or not all(isinstance(item, str) for item in files):
        raise GenerationError(f"{OWNERSHIP_INDEX}: files must be an array of paths")
    result: set[Path] = set()
    for item in files:
        relative = Path(item)
        _validate_relative_path(relative)
        result.add(relative)
    return result


def _stale_generated_files(root: Path, expected: dict[Path, str]) -> set[Path]:
    stale = {
        relative
        for relative in _load_ownership_index(root)
        if relative not in expected and os.path.lexists(root / relative)
    }
    if not (root / CLAUDE_MARKETPLACE).is_file():
        return stale
    for entry in _marketplace_entries(root):
        source = entry.get("source")
        if not isinstance(source, str):
            continue
        plugin_dir = resolve_local_source(root, source)
        for scan_root in (plugin_dir / "skills", plugin_dir / ".codex" / "skills"):
            if not scan_root.is_dir() or scan_root.is_symlink():
                continue
            for path in scan_root.rglob("*"):
                if path.is_file() and not path.is_symlink():
                    relative = path.relative_to(root)
                    if relative not in expected and _has_generated_marker(path):
                        stale.add(relative)
    return stale


def check_generated_files(root: Path, expected: dict[Path, str]) -> list[Path]:
    """Return every missing, modified, or stale generated path."""
    root = root.resolve()
    drift: set[Path] = set()
    for relative, content in expected.items():
        try:
            if _read_text(root / relative) != content:
                drift.add(relative)
        except FileNotFoundError:
            drift.add(relative)
    drift.update(_stale_generated_files(root, expected))
    return sorted(drift, key=Path.as_posix)


def _remove_empty_parents(path: Path, stop: Path) -> None:
    parent = path.parent
    while parent != stop and parent.is_relative_to(stop):
        try:
            parent.rmdir()
        except OSError:
            break
        parent = parent.parent


def _atomic_write(path: Path, content: str) -> None:
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(content.encode("utf-8"))
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
        directory_flag = getattr(os, "O_DIRECTORY", None)
        if directory_flag is not None:
            directory_descriptor = os.open(path.parent, os.O_RDONLY | directory_flag)
            try:
                os.fsync(directory_descriptor)
            finally:
                os.close(directory_descriptor)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


@contextmanager
def _generation_lock(root: Path) -> Iterator[None]:
    lock_path = _safe_path(root, LOCK_FILE, create_parents=True)
    flags = os.O_RDWR | os.O_CREAT | getattr(os, "O_NOFOLLOW", 0)
    try:
        descriptor = os.open(lock_path, flags, 0o600)
    except OSError as error:
        raise GenerationError(f"unable to open generation lock: {error}") from error
    try:
        lock_stream = os.fdopen(descriptor, "r+b")
    except OSError as error:
        os.close(descriptor)
        raise GenerationError(f"unable to wrap generation lock: {error}") from error
    with lock_stream:
        try:
            portalocker.lock(lock_stream, portalocker.LOCK_EX)
        except (OSError, portalocker.exceptions.LockException) as error:
            raise GenerationError(f"unable to acquire generation lock: {error}") from error
        try:
            yield
        finally:
            portalocker.unlock(lock_stream)


def write_generated_files(root: Path, expected: dict[Path, str]) -> None:
    """Write expected files and remove only stale generator-owned files."""
    root = root.resolve()
    root.mkdir(parents=True, exist_ok=True)
    with _generation_lock(root):
        destinations: dict[Path, Path] = {}
        originals: dict[Path, bytes | None] = {}
        for relative, content in expected.items():
            path = _safe_path(root, relative, create_parents=True)
            destinations[relative] = path
            if not path.exists():
                originals[relative] = None
                continue
            try:
                existing = path.read_bytes()
            except OSError as error:
                raise GenerationError(f"unable to read {relative}: {error}") from error
            originals[relative] = existing
            is_shared_metadata = path.name == "openai.yaml" and ".codex" not in relative.parts
            if (
                is_shared_metadata
                and existing != content.encode("utf-8")
                and not _has_generated_marker(path)
            ):
                raise GenerationError(f"refusing to overwrite human-authored metadata: {relative}")

        stale = _stale_generated_files(root, expected)
        stale_originals: dict[Path, bytes] = {}
        for relative in stale:
            path = _safe_path(root, relative)
            try:
                stale_originals[relative] = path.read_bytes()
            except OSError as error:
                raise GenerationError(f"unable to read stale file {relative}: {error}") from error

        changed: list[Path] = []
        removed: list[Path] = []
        try:
            for relative, content in expected.items():
                if originals[relative] == content.encode("utf-8"):
                    continue
                _atomic_write(destinations[relative], content)
                changed.append(relative)
            for relative in sorted(stale, key=Path.as_posix, reverse=True):
                path = _safe_path(root, relative)
                path.unlink()
                removed.append(relative)
                _remove_empty_parents(path, root)
        except BaseException as error:
            for relative in reversed(changed):
                path = _safe_path(root, relative, create_parents=True)
                original = originals[relative]
                if original is None:
                    path.unlink(missing_ok=True)
                else:
                    _atomic_write(path, original.decode("utf-8"))
            for relative in removed:
                path = _safe_path(root, relative, create_parents=True)
                _atomic_write(path, stale_originals[relative].decode("utf-8"))
            if isinstance(error, GenerationError):
                raise
            raise GenerationError(f"generation transaction failed: {error}") from error


def _summarize(root: Path, expected: dict[Path, str]) -> str:
    entries = _marketplace_entries(root)
    local_plugins = sum(isinstance(entry.get("source"), str) for entry in entries)
    adapters = sum(path.name == "SKILL.md" for path in expected)
    policy_files = sum(path.name == "openai.yaml" for path in expected)
    return (
        f"{local_plugins} local plugins, "
        f"{len(entries) - local_plugins} external plugins, "
        f"{adapters} adapters, "
        f"{policy_files} policy files"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    try:
        expected = build_expected_files(root)
        summary = _summarize(root, expected)
        if args.check:
            drift = check_generated_files(root, expected)
            if drift:
                print("Codex marketplace metadata is out of date:", file=sys.stderr)
                for path in drift:
                    print(f"  {path.as_posix()}", file=sys.stderr)
                return 1
        else:
            write_generated_files(root, expected)
    except (GenerationError, OSError, UnicodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    action = "Validated" if args.check else "Generated"
    print(f"{action} Codex marketplace: {summary}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
